name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get install build-essential libssl-dev libgtest-dev
        sudo apt-get install cmake
    - name: build library
      run: |
        git clone https://github.com/SRombauts/SQLiteCpp.git
        mkdir -p SQLiteCpp/build
        cd SQLiteCpp/build
        cmake ..
        make
    - name: create db
      run: |
          sqlite3 db/flower.db < db/flower.sql
          sqlite3 tests/test.db < db/flower.sql
    - name: build app
      run: |
         cmake CMakeLists.txt
         make
    - name: tests
      working-directory: ./tests
      run: |
          cmake CMakeLists.txt
          make
          ./tests
