name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get install build-essential libssl-dev
        sudo apt-get install cmake
    - name: build library
      run: |
        git clone https://github.com/SRombauts/SQLiteCpp.git
        mkdir -p SQLiteCpp/build
        cd SQLiteCpp/build
        cmake ..
        make
